### ISSUE TITLE
Problems with terminals and process subsitution

### ISSUE THREAD

**Issue by slavistan** [romkatv/zshi#1]
Hi,

while tinkering around with `zshi` trying to wrap it into a terminal startup, I noticed a few odd things, which are beyond my comprehension. Suppose I wanted to start an interactive zsh session in a new terminal and set `x=1` during startup, like so: `kitty zshi <(echo 'x=1') -i`. The problem is that, depending on the terminal and the process substitution construct (`<()`, or `=()`) it works only sometimes.

```
### kitty

kitty zshi <(echo 'x=1') -i
# does NOT work. Spawns the terminal and prints
# '/proc/self/fd/11:12: job table full'

kitty zshi =(echo 'x=1') -i
# works.


### gnome-terminal

gnome-terminal -- zshi <(echo 'x=1') -i
# does NOT work. Spawns the terminal and prints
# '/proc/self/fd/11:12: job table full'

gnome-terminal -- zshi =(echo 'x=1') -i
# does NOT work. Spawns the terminal and prints
# '/tmp/zsh.5dLpmtLurU/.zshrc:source:13: no such file or directory: /tmp/zshA1z5cT'


### suckless terminal

st zshi <(echo 'x=1') -i
st zshi =(echo 'x=1') -i
# both work
```

Any ideas on what's going on here? Everything works as expected if I write `x=1` to a physical file `/tmp/foo` and call `zshi` on it: `zsh /tmp/foo -i`. I cannot even tell whether there's a problem with `zshi` and I beg your pardon in advance if I'm mistaken about it.

Thank you and kind regards.

**Comment by romkatv** [comment]
When you use `<(...)` or `=(...)` as an argument of a command, the file is deleted as soon as the command returns. The problem is that `gnome-terminal` (and other terminals) returns without waiting for the shell, so the temporary file ends up deleted too early.

**Comment by slavistan** [comment]
Ah, that quite settles the matter. Thank you.
