### ISSUE TITLE
How can I install this?

### ISSUE THREAD

**Issue by Nathan-ma** [romkatv/zshi#2]
Hi, this seems like a wonderful script! 

Currently, I'm creating a `Terminal.sh` on each folder and setting it on the `code-workspace` file.

```
# like this
"terminal.integrated.profiles.osx": {
      "bash": {
        "path": "bash",
        "args": [
          "--init-file",
          "./Terminal.sh"
        ],
        "icon": "terminal-bash"
      }
```

I've always wanted to do the same with zsh. I came across this repo and I think this might be what I'm looking for.

I just down know How I can install this. Can I suggest some extra instructions on the README.md?

Thank you!

**Comment by romkatv** [comment]
It's a script. You can install it like any other script: download and make it executable.
